-- Administrable FZAC assistant knowledge with private quality feedback.
-- Additive and idempotent: no operational tables or existing rows are removed.

begin;

create table if not exists public.assistant_knowledge (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 2 and 100),
  topic text not null check (char_length(topic) between 2 and 60),
  intent text not null default 'store_policy' check (intent in (
    'greeting', 'delivery', 'payment', 'stock', 'price', 'estimate',
    'order_status', 'returns', 'store_policy', 'human', 'product_search', 'fallback'
  )),
  keywords text[] not null default '{}',
  phrases text[] not null default '{}',
  answer text not null check (char_length(answer) between 20 and 1200),
  alternate_answer text check (alternate_answer is null or char_length(alternate_answer) between 20 and 1200),
  source_label text not null check (char_length(source_label) between 2 and 100),
  source_href text not null check (source_href ~ '^/[A-Za-z0-9_?=&/%.-]*$' and source_href !~ '^//'),
  actions jsonb not null default '[]'::jsonb check (jsonb_typeof(actions) = 'array'),
  active boolean not null default true,
  version integer not null default 1 check (version > 0),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists assistant_knowledge_active_topic_idx
on public.assistant_knowledge (active, topic, updated_at desc);

create table if not exists public.assistant_knowledge_versions (
  id bigint generated by default as identity primary key,
  knowledge_id uuid not null references public.assistant_knowledge(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (knowledge_id, version)
);

create table if not exists public.assistant_feedback (
  id uuid primary key default gen_random_uuid(),
  trace_id uuid not null unique,
  conversation_id uuid references public.chat_conversations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id uuid,
  knowledge_slug text,
  rating text not null check (rating in ('UP', 'DOWN')),
  created_at timestamptz not null default now(),
  check (user_id is not null or visitor_id is not null)
);

create index if not exists assistant_feedback_created_idx
on public.assistant_feedback (created_at desc);

create or replace function public.archive_assistant_knowledge_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.assistant_knowledge_versions (knowledge_id, version, snapshot, changed_by)
  values (old.id, old.version, to_jsonb(old), new.updated_by)
  on conflict (knowledge_id, version) do nothing;
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists archive_assistant_knowledge_version_trigger on public.assistant_knowledge;
create trigger archive_assistant_knowledge_version_trigger
before update on public.assistant_knowledge
for each row execute function public.archive_assistant_knowledge_version();

alter table public.assistant_knowledge enable row level security;
alter table public.assistant_knowledge force row level security;
alter table public.assistant_knowledge_versions enable row level security;
alter table public.assistant_knowledge_versions force row level security;
alter table public.assistant_feedback enable row level security;
alter table public.assistant_feedback force row level security;

drop policy if exists "public active assistant knowledge" on public.assistant_knowledge;
create policy "public active assistant knowledge"
on public.assistant_knowledge for select
using (active = true or public.is_admin());

drop policy if exists "admin assistant knowledge all" on public.assistant_knowledge;
create policy "admin assistant knowledge all"
on public.assistant_knowledge for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin assistant knowledge versions read" on public.assistant_knowledge_versions;
create policy "admin assistant knowledge versions read"
on public.assistant_knowledge_versions for select
using (public.is_admin());

drop policy if exists "admin assistant feedback read" on public.assistant_feedback;
create policy "admin assistant feedback read"
on public.assistant_feedback for select
using (public.is_admin());

revoke all on table public.assistant_knowledge from anon, authenticated;
grant select on table public.assistant_knowledge to anon, authenticated;
grant all on table public.assistant_knowledge to service_role;

revoke all on table public.assistant_knowledge_versions from anon, authenticated;
grant select on table public.assistant_knowledge_versions to authenticated;
grant all on table public.assistant_knowledge_versions to service_role;

revoke all on table public.assistant_feedback from anon, authenticated;
grant select on table public.assistant_feedback to authenticated;
grant all on table public.assistant_feedback to service_role;

grant usage, select on sequence public.assistant_knowledge_versions_id_seq to service_role;

comment on table public.assistant_knowledge is
  'Published, non-sensitive FZAC answers used by the customer assistant.';
comment on table public.assistant_feedback is
  'Private assistant quality signals. Never store message content, credentials or card data.';

insert into public.assistant_knowledge (
  slug, title, topic, intent, keywords, phrases, answer, alternate_answer,
  source_label, source_href, actions, active, published_at
)
values
  (
    'buying-process', 'Cómo comprar', 'Compra', 'store_policy',
    array['comprar','compra','proceso','pasos','carrito','checkout'],
    array['como comprar','como hago una compra','pasos para comprar'],
    'La compra se completa en cuatro etapas: elegís los productos, confirmás tus datos y modalidad de entrega, FZAC valida stock y precios, y finalmente pagás online o generás el pedido para coordinar. Podés seguir cada pedido desde Mi cuenta.',
    'Para comprar, agregá materiales al carrito, revisá cantidades y unidad de venta, completá tus datos y elegí entrega y pago. El backend vuelve a validar precio y stock antes de crear el pedido.',
    'Cómo comprar', '/como-comprar',
    '[{"label":"Ver productos","href":"/productos"},{"label":"Cómo comprar","href":"/como-comprar"},{"label":"Ver carrito","href":"/carrito"}]'::jsonb,
    true, now()
  ),
  (
    'payment-overview', 'Medios de pago', 'Pagos', 'payment',
    array['pago','pagar','medio','mercado','tarjeta','transferencia','whatsapp'],
    array['medios de pago','formas de pago','como puedo pagar','como pago'],
    'FZAC ofrece pago online con Mercado Pago, pedido pendiente por transferencia y coordinación por WhatsApp. Solo Mercado Pago inicia una operación con el proveedor; transferencia y WhatsApp no abren Mercado Pago.',
    'Podés pagar online mediante Mercado Pago o generar un pedido para transferir o coordinar por WhatsApp. El stock no se descuenta por una operación pendiente o rechazada.',
    'Medios de pago', '/medios-de-pago',
    '[{"label":"Ver medios de pago","href":"/medios-de-pago"},{"label":"Ir al checkout","href":"/checkout"},{"label":"Seguridad del pago","message":"¿FZAC guarda los datos de mi tarjeta?"}]'::jsonb,
    true, now()
  ),
  (
    'bank-transfer', 'Transferencia FZAC', 'Pagos', 'payment',
    array['transferencia','transferir','alias','cbu','comprobante','bancaria'],
    array['pagar por transferencia','pagar con transferencia','datos para transferir','enviar comprobante'],
    'Al elegir transferencia, FZAC genera un pedido pendiente y no te redirige a Mercado Pago. Administración revisa el pedido y te comunica los datos para transferir; la acreditación y el stock se confirman después de validar el pago.',
    'La transferencia funciona como pedido pendiente: primero se crea la orden, luego FZAC informa los datos bancarios y valida el comprobante. No compartas comprobantes ni datos bancarios dentro del chatbot.',
    'Medios de pago', '/medios-de-pago',
    '[{"label":"Generar pedido","href":"/checkout"},{"label":"Ver medios de pago","href":"/medios-de-pago"},{"label":"Consultar pedido","href":"/cuenta/pedidos"}]'::jsonb,
    true, now()
  ),
  (
    'card-security', 'Seguridad de pagos', 'Pagos', 'payment',
    array['tarjeta','cvv','numero','seguridad','guardar','datos','brick'],
    array['guardan mi tarjeta','datos de tarjeta','pago seguro','guardar cvv'],
    'FZAC no guarda número de tarjeta, vencimiento ni CVV. Los datos se procesan mediante componentes oficiales del proveedor de pagos y la confirmación final se verifica desde el servidor y el webhook.',
    'Los datos sensibles de tarjeta no pasan a la base de FZAC. El proveedor tokeniza el pago y FZAC solo conserva referencias y estados necesarios para administrar la compra.',
    'Seguridad de pagos', '/medios-de-pago',
    '[{"label":"Ver seguridad de pagos","href":"/medios-de-pago"},{"label":"Política de privacidad","href":"/privacidad"},{"label":"Ir al checkout","href":"/checkout"}]'::jsonb,
    true, now()
  ),
  (
    'delivery-policy', 'Envíos y retiros', 'Entrega', 'delivery',
    array['envio','entrega','flete','domicilio','direccion','distancia','zona'],
    array['como funciona el envio','hacen envios','envio a domicilio','costo de envio'],
    'Para envío a domicilio se necesita una dirección completa. La modalidad y el costo se informan antes de confirmar; si no hay una cotización automática disponible, el pedido queda para coordinar y FZAC no inventa un valor de flete.',
    'Los envíos se revisan según dirección, distancia y características del pedido. Cargá calle, número, ciudad y teléfono; cuando la cotización no está automatizada, FZAC confirma el costo antes de cerrar la operación.',
    'Envíos y retiros', '/envios-y-retiros',
    '[{"label":"Envíos y retiros","href":"/envios-y-retiros"},{"label":"Cargar dirección","href":"/cuenta/direcciones"},{"label":"Prefiero retirar","message":"Quiero retirar mi pedido"}]'::jsonb,
    true, now()
  ),
  (
    'pickup-policy', 'Retiro coordinado', 'Entrega', 'delivery',
    array['retiro','retirar','buscar','local','deposito','direccion'],
    array['retiro en el local','pasar a buscar','retirar pedido','retiro coordinado'],
    'El retiro es coordinado: no exige dirección de entrega ni suma flete. FZAC valida stock, prepara el pedido y avisa cuándo está listo; la persona autorizada debe presentar los datos solicitados para retirarlo.',
    'Si elegís retiro, completás solo tus datos de contacto y el medio de pago. Esperá la confirmación de preparación antes de acercarte, porque una orden creada todavía puede estar pendiente de stock o pago.',
    'Envíos y retiros', '/envios-y-retiros',
    '[{"label":"Elegir retiro","href":"/checkout"},{"label":"Ver mi pedido","href":"/cuenta/pedidos"},{"label":"Envíos y retiros","href":"/envios-y-retiros"}]'::jsonb,
    true, now()
  ),
  (
    'returns-policy', 'Cambios y devoluciones', 'Postventa', 'returns',
    array['devolucion','devolver','cambio','garantia','dañado','roto','reembolso'],
    array['quiero devolver','solicitar la devolucion','devolucion del pedido','producto dañado','hacer un cambio','pedir reembolso'],
    'Para solicitar revisión, conservá el comprobante e informá pedido, producto, motivo y estado de la mercadería. FZAC registra el caso y revisa uso, embalaje, entrega y posibles excepciones antes de resolver cambio o reembolso.',
    'Los cambios y devoluciones se gestionan mediante una solicitud formal. Tener número de pedido, comprobante y fotos facilita la revisión; el reembolso, si corresponde, se procesa por el medio original.',
    'Cambios y devoluciones', '/cambios-y-devoluciones',
    '[{"label":"Solicitar revisión","href":"/arrepentimiento"},{"label":"Ver condiciones","href":"/cambios-y-devoluciones"},{"label":"Mis solicitudes","href":"/cuenta/solicitudes"}]'::jsonb,
    true, now()
  ),
  (
    'withdrawal-right', 'Botón de arrepentimiento', 'Postventa', 'returns',
    array['arrepentimiento','revocar','revocacion','cancelar','diez','dias'],
    array['boton de arrepentimiento','derecho de arrepentimiento','cancelar compra online'],
    'El Botón de arrepentimiento permite iniciar una solicitud sobre una compra a distancia sin necesidad de ingresar al panel. La política vigente informa un plazo de diez días y FZAC entrega una constancia con número de trámite.',
    'Podés iniciar el arrepentimiento desde el formulario público. Indicá tus datos y el pedido; la solicitud queda registrada para revisión y seguimiento, sin exigir condiciones adicionales para comenzar el trámite.',
    'Botón de arrepentimiento', '/arrepentimiento',
    '[{"label":"Iniciar solicitud","href":"/arrepentimiento"},{"label":"Leer condiciones","href":"/cambios-y-devoluciones"},{"label":"Ver términos","href":"/terminos"}]'::jsonb,
    true, now()
  ),
  (
    'privacy-policy', 'Política de privacidad', 'Legal', 'store_policy',
    array['privacidad','datos','personales','eliminar','cuenta','informacion','cookies'],
    array['politica de privacidad','eliminar mis datos','que datos guardan','datos personales'],
    'FZAC utiliza datos de identidad, contacto, cuenta y compra para operar pedidos, pagos, entregas y atención. No guarda datos de tarjeta. Podés consultar la política para conocer conservación, proveedores y cómo solicitar acceso, rectificación o supresión.',
    'La información personal se usa para autenticación, pedidos, pagos, entrega y soporte. El acceso administrativo está restringido y los derechos sobre tus datos se gestionan por los canales indicados en la Política de privacidad.',
    'Política de privacidad', '/privacidad',
    '[{"label":"Política de privacidad","href":"/privacidad"},{"label":"Ajustes de cuenta","href":"/cuenta/ajustes"},{"label":"Contacto FZAC","href":"/contacto"}]'::jsonb,
    true, now()
  ),
  (
    'terms-policy', 'Términos y condiciones', 'Legal', 'store_policy',
    array['terminos','condiciones','legal','politica','garantia','consumidor'],
    array['terminos y condiciones','condiciones de compra','defensa del consumidor'],
    'Los Términos FZAC explican identificación del proveedor, catálogo, disponibilidad, pagos, entrega, retiro, arrepentimiento, garantías, reembolsos y datos personales. La versión completa está disponible antes de confirmar la compra.',
    'Las condiciones de compra reúnen las reglas vigentes sobre precio, stock, pago, entrega, garantía y derechos del consumidor. Para una decisión legal o un reclamo concreto, revisá siempre el texto completo.',
    'Términos y condiciones', '/terminos',
    '[{"label":"Ver términos","href":"/terminos"},{"label":"Cambios y devoluciones","href":"/cambios-y-devoluciones"},{"label":"Política de privacidad","href":"/privacidad"}]'::jsonb,
    true, now()
  )
on conflict (slug) do nothing;

commit;
