-- SUPERSEDED / INTENTIONALLY NO-OP
--
-- This migration was never applied to production and its uniqueness rules for
-- normalized full_name and phone are not valid business constraints: different
-- customers may legitimately share a name or telephone number.
--
-- Email/account identity remains governed by Supabase Auth and the current
-- profile integrity/security controls. Do not recreate unique indexes on
-- profiles.full_name or normalized phone.
--
-- Keep this version as a no-op marker so a future include-all push cannot apply
-- the obsolete uniqueness rules.
