-- SUPERSEDED / INTENTIONALLY NO-OP
--
-- This historical migration was committed to the repository but was never
-- applied to the production Supabase project. Applying it now would reintroduce
-- outdated grants and SECURITY DEFINER definitions.
--
-- Its still-required behavior has been reconciled by later production
-- migrations, including:
--   * 20260915184832_force_rls_current_app_tables
--   * 20260915202457_reduce_transactional_table_grants
--   * 20260915203119_least_privilege_public_api_grants
--   * 20260921035631_restore_required_server_rpcs
--
-- Keep this version as a no-op marker so an include-all migration push cannot
-- execute the obsolete SQL accidentally.
