-- SUPERSEDED / INTENTIONALLY NO-OP
--
-- This historical migration was never applied to production and targets an
-- older schema (including objects/columns that no longer match the current
-- application). Running it today would create drift and can break valid flows.
--
-- Current, production-compatible integrity controls were reconciled in later
-- migrations, especially:
--   * 20260915185438_guard_paid_orders_require_items
--   * 20260921035631_restore_required_server_rpcs
--   * 20260921035915_harden_review_submission
--   * 20260921040008_restrict_notification_updates
--   * 20260921143107_reconcile_runtime_integrity_guards
--
-- Keep this version as a no-op marker so a future include-all push remains safe.
